/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assets/axe.glb --types 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import axeUrl from "./assets/axe.glb?url";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1001_1: THREE.Mesh;
    Mesh_1001_2: THREE.Mesh;
  };
  materials: {
    material_2: THREE.MeshStandardMaterial;
    material_3: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(axeUrl) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_1001_1.geometry}
        material={materials.material_2}
      />
      <mesh
        geometry={nodes.Mesh_1001_2.geometry}
        material={materials.material_3}
      />
    </group>
  );
}

useGLTF.preload(axeUrl);
